### ISSUE TITLE
How to implement this in OpenWrt sources?

### ISSUE THREAD

**Issue by ghost** [DonAnthonyLee/npi_oled_panel#1]
Nice of you to share but as it stands its pretty useless for anyone as you're forcing us to use whatever you compiled.

Can you provide the patches needed to build our own OpenWrt with OLED support for the NEO2?

Thanks.

**Comment by DonAnthonyLee** [comment]
Anything you need I've put it to "https://github.com/DonAnthonyLee/openwrt/" a long time ago. This repo IS NOT aiming to help anyone to use offical OLED hat for NEO/NEO2, it's recommended that you should ask for FriendlyElec's help.
